//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Melchior {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Melchior.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add friend.
        /// </summary>
        public static string Add_friend {
            get {
                return ResourceManager.GetString("Add_friend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add person.
        /// </summary>
        public static string Add_person {
            get {
                return ResourceManager.GetString("Add_person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        public static string Audio {
            get {
                return ResourceManager.GetString("Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization error. Please make sure that you&apos;ve entered the correct phone or email and password and try again..
        /// </summary>
        public static string Authorization_error {
            get {
                return ResourceManager.GetString("Authorization_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call {phone}.
        /// </summary>
        public static string Call_phone {
            get {
                return ResourceManager.GetString("Call_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change chat.
        /// </summary>
        public static string Change_chat {
            get {
                return ResourceManager.GetString("Change_chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change photo.
        /// </summary>
        public static string Change_photo {
            get {
                return ResourceManager.GetString("Change_photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose existing photo.
        /// </summary>
        public static string Choose_existing_photo {
            get {
                return ResourceManager.GetString("Choose_existing_photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decline request.
        /// </summary>
        public static string Decline_request {
            get {
                return ResourceManager.GetString("Decline_request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete friend.
        /// </summary>
        public static string Delete_friend {
            get {
                return ResourceManager.GetString("Delete_friend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable notification sound for the next {time}.
        /// </summary>
        public static string Disable_notification {
            get {
                return ResourceManager.GetString("Disable_notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        public static string Document {
            get {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error uploading.
        /// </summary>
        public static string Error_uploading {
            get {
                return ResourceManager.GetString("Error_uploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For fast, free and convenient messaging with friends and contacts.
        /// </summary>
        public static string Fast_Messaging {
            get {
                return ResourceManager.GetString("Fast_Messaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward.
        /// </summary>
        public static string Forward {
            get {
                return ResourceManager.GetString("Forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forwarded message.
        /// </summary>
        public static string Forwarded_message {
            get {
                return ResourceManager.GetString("Forwarded_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend requests.
        /// </summary>
        public static string Friend_requests {
            get {
                return ResourceManager.GetString("Friend_requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends.
        /// </summary>
        public static string Friends {
            get {
                return ResourceManager.GetString("Friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In-app notifications.
        /// </summary>
        public static string In_app_notifications {
            get {
                return ResourceManager.GetString("In_app_notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading messages...
        /// </summary>
        public static string Loading_messages {
            get {
                return ResourceManager.GetString("Loading_messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string Log_in {
            get {
                return ResourceManager.GetString("Log_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message was not sent.
        /// </summary>
        public static string Message_was_not_sent {
            get {
                return ResourceManager.GetString("Message_was_not_sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New account.
        /// </summary>
        public static string New_account {
            get {
                return ResourceManager.GetString("New_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No messages yet.
        /// </summary>
        public static string No_messages_yet {
            get {
                return ResourceManager.GetString("No_messages_yet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {num} members.
        /// </summary>
        public static string Num_members {
            get {
                return ResourceManager.GetString("Num_members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string Online {
            get {
                return ResourceManager.GetString("Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People you may know.
        /// </summary>
        public static string People_you_may_know {
            get {
                return ResourceManager.GetString("People_you_may_know", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        public static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push notifications.
        /// </summary>
        public static string Push_notifications {
            get {
                return ResourceManager.GetString("Push_notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove attachment.
        /// </summary>
        public static string Remove_attachment {
            get {
                return ResourceManager.GetString("Remove_attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests.
        /// </summary>
        public static string Requests {
            get {
                return ResourceManager.GetString("Requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for your friends and contacts among all registred users.
        /// </summary>
        public static string Search_among_all_registred_users {
            get {
                return ResourceManager.GetString("Search_among_all_registred_users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send a message.
        /// </summary>
        public static string Send_a_message {
            get {
                return ResourceManager.GetString("Send_a_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send invitation.
        /// </summary>
        public static string Send_invitation {
            get {
                return ResourceManager.GetString("Send_invitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share location.
        /// </summary>
        public static string Share_location {
            get {
                return ResourceManager.GetString("Share_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string Sign_up {
            get {
                return ResourceManager.GetString("Sign_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound.
        /// </summary>
        public static string Sound {
            get {
                return ResourceManager.GetString("Sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync contacts.
        /// </summary>
        public static string Sync_contacts {
            get {
                return ResourceManager.GetString("Sync_contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync your phone contacts with your VK friends list.
        /// </summary>
        public static string Sync_your_phone_contacts {
            get {
                return ResourceManager.GetString("Sync_your_phone_contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take photo.
        /// </summary>
        public static string Take_photo {
            get {
                return ResourceManager.GetString("Take_photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try again.
        /// </summary>
        public static string Try_again {
            get {
                return ResourceManager.GetString("Try_again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading attachments...
        /// </summary>
        public static string Uploading_attachments {
            get {
                return ResourceManager.GetString("Uploading_attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not registred yet. You can send an invitation..
        /// </summary>
        public static string User_is_not_registred_yet {
            get {
                return ResourceManager.GetString("User_is_not_registred_yet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {user} is typing....
        /// </summary>
        public static string User_is_typing {
            get {
                return ResourceManager.GetString("User_is_typing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {user} was last seen {time} ago.
        /// </summary>
        public static string User_was_last_seen_time_ago {
            get {
                return ResourceManager.GetString("User_was_last_seen_time_ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vibrate.
        /// </summary>
        public static string Vibrate {
            get {
                return ResourceManager.GetString("Vibrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write a message.
        /// </summary>
        public static string Write_a_message {
            get {
                return ResourceManager.GetString("Write_a_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your surname.
        /// </summary>
        public static string Your_lastname {
            get {
                return ResourceManager.GetString("Your_lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your name.
        /// </summary>
        public static string Your_name {
            get {
                return ResourceManager.GetString("Your_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password.
        /// </summary>
        public static string Your_password {
            get {
                return ResourceManager.GetString("Your_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your phone number.
        /// </summary>
        public static string Your_phone_number {
            get {
                return ResourceManager.GetString("Your_phone_number", resourceCulture);
            }
        }
    }
}
